scripts: add timeout, switch to default editor

diff --git a/sh/monitor-boinc b/sh/monitor-boinc
--- a/sh/monitor-boinc
+++ b/sh/monitor-boinc
@@ -16,7 +16,8 @@ STARTUP=${STARTUP:-start-boinc}
 
 case "$1" in
 edit)
-    vim "$0" || vi "$0" || nano "$0" || ( echo "Editor not found" && exit 1 )
+    # check update-alternatives
+    editor "$0" || ( echo "Editor not found" && exit 1 )
     exit
     ;;
 esac
@@ -25,7 +26,7 @@ cd "$APPDATA"
 
 pkill -x main
 pkill -x termux-api
-echo "Current temp: $(termux-battery-status 2>/dev/null | jq .temperature)"
+echo "Current temp: $(timeout 5 termux-battery-status 2>/dev/null | jq .temperature)"
 echo "Maximum temp: $(grep '^MAX_TEMP=' $(which $STARTUP) | sed -e 's/MAX_TEMP=//')"
 echo
 
